version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: Portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./portfolio-backend/portfolio-backend
    container_name: portfolio
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Portfolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: helloworld!
    depends_on:
      - db

  frontend:
    build: ./portfolio-neeraj
    container_name: portfolio
    environment:
      VITE_API_URL: http://backend:8080
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
